version: '3'
services:
  api: 
    container_name: nestjs-app
    restart: unless-stopped
    build: 
        context: ./
    image: nestjs-api
    ports:
      - '1339:3000'
 # Run the caddy server        
    caddy:
        image: caddy:latest
        container_name: caddy-service
        restart: unless-stopped
        extra_hosts:
          - "host.docker.internal:host-gateway"
        depends_on:
        - api
        ports:
            - "1337:1337"
        volumes:            
        - $PWD/Caddyfile:/etc/caddy/Caddyfile
        - $PWD/site:/srv
        - caddy_data:/data
        - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: 